### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ItsAloof** [ItsAloof/KitPvP#1]
**Things to-do**:
 - [ ] Ability to read Schematic file or Ability to setup premade arenas
 - [ ] Setup competitive matches (save player location, inventory, etc.)
 - [ ] Rank system
 - [ ] Betting on matches
 - [ ] Commands for creating arena, deleting arena, checking current matches, arena list, player stats, casual comp challenge

**More to be added later**
